import { LegalPageLayout } from "@/components/layout/LegalPageLayout";

export default function Terms() {
  return (
    <LegalPageLayout
      title="Terms of Service"
      subtitle="Rules governing use of the VitaSync platform"
      date="April 8, 2026"
    >
      <h2>1. Preamble and Purpose</h2>
      <p>These Terms of Service ("Terms") govern your access to and use of the VitaSync platform, accessible at vitasync.ai ("Platform"). VitaSync is an AI-powered wellness and nutrition platform offering a personalized AI coach, supplement tracking, informational blood test analysis, an online supplement store, and daily wellness tools.</p>

      <div className="p-4 rounded-xl bg-destructive/10 border border-destructive/20 my-6">
        <p className="text-foreground font-medium">
          ⚠️ IMPORTANT NOTICE: VitaSync is a wellness and lifestyle information platform. It is NOT a medical device under EU Regulation 2017/745 (MDR) or the US FDA 21 CFR Part 820. The information and recommendations provided do NOT constitute medical advice, diagnosis, or treatment. VitaSync is NOT a prescription service. Always consult a qualified healthcare professional before making any decisions about your health or diet.
        </p>
      </div>

      <p>By creating an account or using the Platform, the User unconditionally accepts these Terms as well as the Privacy Policy, the Cookie Policy, and, where applicable, the Terms of Sale.</p>

      <div className="p-4 rounded-xl bg-primary/5 border border-primary/10 my-4">
        <p className="text-foreground">
          <strong>Geographic scope:</strong> The Platform (AI coach, tracking) is accessible internationally. However, the VitaSync shop ships exclusively within the United States (48 contiguous states, excluding Alaska and Hawaii) through our fulfillment partner Supliful. Users outside the USA can use the AI coach in freemium/subscription mode but cannot order physical products.
        </p>
      </div>

      <h2>2. Definitions</h2>
      <ul>
        <li><strong>"Platform"</strong>: the VitaSync website and all of its features.</li>
        <li><strong>"User"</strong>: any adult individual (18 years or older) registered on the Platform.</li>
        <li><strong>"AI Coach"</strong>: the VitaSync artificial intelligence assistant, powered by Google Gemini models.</li>
        <li><strong>"Stack"</strong>: the set of dietary supplements tracked by a User.</li>
        <li><strong>"Check-in"</strong>: the daily wellness log submitted by the User.</li>
        <li><strong>"Products"</strong>: dietary supplements sold through the VitaSync shop (US shipping only).</li>
        <li><strong>"AI System"</strong>: any component using artificial intelligence (Coach, blood test analyses, recommendations).</li>
      </ul>

      <h2>3. Registration and User Account</h2>
      <p>3.1 Registration is restricted to adults (18 years or older). The User agrees to provide accurate and up-to-date information. Passwords must contain at least 8 characters with at least one uppercase letter, one number, and one special character.</p>
      <p>3.2 After registration, the User is invited to complete a health questionnaire (onboarding) to enable personalized recommendations. This questionnaire is voluntary but necessary to receive tailored recommendations.</p>
      <p>3.3 The User may request deletion of their account at any time through the dashboard settings. Such deletion results in the erasure of all data in accordance with the Privacy Policy and applicable privacy laws (GDPR Art. 17 for EU users; CCPA/CPRA for California residents).</p>

      <h2>4. Description of Services</h2>

      <h3>4.1 VitaSync AI Coach</h3>
      <p>The AI Coach is a conversational wellness and nutrition assistant providing personalized recommendations based on the User's profile. Several model tiers are available depending on the subscription: Free (Lite) and Pro (full access to the advanced AI coach).</p>
      <div className="p-4 rounded-xl bg-primary/5 border border-primary/10 my-4">
        <p className="text-foreground">
          <strong>AI Transparency (EU AI Act, Art. 50):</strong> You are interacting with an artificial intelligence system powered by Google Gemini. This is not a human healthcare professional. All responses are generated by AI technology. Recommendations are for informational and educational purposes only.
        </p>
      </div>

      <h3>4.2 Supplement Tracker</h3>
      <p>The User can add, track, and manage their daily dietary supplements with intake reminders. A logging system allows tracking of adherence over time.</p>

      <h3>4.3 Blood Test Analysis (informational only)</h3>
      <p>The User may upload blood test results in PDF format. The AI provides general educational context regarding the values. This feature does NOT constitute medical interpretation, diagnosis, or clinical evaluation. Only a licensed healthcare professional can properly interpret results within the context of a complete medical history.</p>

      <h3>4.4 VitaSync Shop (USA only)</h3>
      <p>VitaSync offers a catalog of dietary supplements through Shopify, with shipping exclusively to the United States. Purchase conditions are governed by the Terms of Sale and the Shipping & Returns Policy.</p>

      <h2>5. Limitations of Liability</h2>
      <div className="p-4 rounded-xl bg-destructive/10 border border-destructive/20 my-4">
        <p className="text-foreground font-medium">⚠️ VitaSync is NOT a medical service. The Platform is not a substitute for a medical consultation under any circumstances.</p>
      </div>
      <p>VitaSync disclaims any liability for damages resulting from the use of AI recommendations without prior validation by a healthcare professional.</p>
      <ul>
        <li>VitaSync does not guarantee the accuracy of AI analyses of blood test results.</li>
        <li>VitaSync cannot be held liable for adverse effects related to the use of dietary supplements.</li>
        <li>VitaSync does not guarantee permanent availability of the Platform.</li>
        <li>Product recommendations are general wellness information, not medical prescriptions.</li>
        <li>The User is solely responsible for how they use the information provided.</li>
        <li>Dietary supplements may interact with medications. The User must consult their physician or pharmacist before adding any new supplement.</li>
      </ul>
      <p><strong>AI Liability:</strong> For EU users, in accordance with Directive (EU) 2024/2853 on product liability (applicable from December 9, 2026), VitaSync will be subject to a strict liability regime for AI-related defects. The limitation of liability clauses in these Terms cannot exclude this statutory liability where it applies. For US users, applicable consumer protection and product liability laws of the User's state of residence apply.</p>

      <h2>6. User Obligations</h2>
      <ul>
        <li>Provide accurate information, particularly regarding allergies and medical conditions.</li>
        <li>Not use the Platform for illegal or unauthorized purposes.</li>
        <li>Not attempt to access other users' data.</li>
        <li>Not misuse the AI Coach beyond its intended purpose (wellness and nutrition).</li>
        <li>Consult a healthcare professional before taking supplements, especially in case of pregnancy, ongoing medical treatment, or pre-existing conditions.</li>
        <li>Immediately report any security vulnerability to <a href="mailto:contact@vitasync.ai">contact@vitasync.ai</a>.</li>
        <li>Not use the Platform if the User is a minor (under 18 years old).</li>
      </ul>

      <h2>7. Pricing & Subscriptions</h2>
      <ul>
        <li><strong>Free:</strong> Free access to basic features (AI Coach Lite, supplement tracking, daily check-ins).</li>
        <li><strong>Pro — $7.99/month:</strong> Full access to the advanced AI Coach, unlimited blood test analyses, interactive quizzes, and in-depth recommendations.</li>
      </ul>
      <p>Supplement purchases through the shop are independent of the subscription and are governed by the Terms of Sale. Subscriptions are managed through Shopify for payment and billing. The User can cancel their subscription at any time from their Shopify account; cancellation takes effect at the end of the current billing period.</p>

      <h2>8. Intellectual Property</h2>
      <p>All elements of the Platform (design, code, text, logos, scientific databases) are the exclusive property of VitaSync or its partners. Any unauthorized reproduction, representation, or exploitation is prohibited in accordance with United States copyright law (17 U.S.C.) and applicable intellectual property laws. The User retains ownership of their personal and health data. By using the Platform, the User grants VitaSync a limited, non-exclusive license to use their data solely for the purpose of providing the service.</p>

      <h2>9. Termination</h2>
      <p>The User may terminate their account at any time. VitaSync reserves the right to suspend or delete an account in case of violation of these Terms, abusive behavior, or attempted fraud. Upon termination, data is processed in accordance with the Privacy Policy.</p>

      <h2>10. Governing Law &amp; Disputes</h2>
      <p>These Terms are governed by the laws of the United States and the State of Delaware, without regard to conflict of law principles. For users residing in the European Union, mandatory consumer protection provisions of their country of residence also apply. Nothing in these Terms affects your rights as a consumer under applicable national law.</p>
      <p>In the event of a dispute, the parties agree to first seek an amicable resolution. For US consumers, disputes may be submitted to binding arbitration under the American Arbitration Association (AAA) rules, except where prohibited by law. EU users may also use the European Online Dispute Resolution platform: <a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noopener noreferrer">https://ec.europa.eu/consumers/odr</a>.</p>

      <h2>11. Changes to These Terms</h2>
      <p>VitaSync reserves the right to modify these Terms at any time. Changes take effect upon publication. The User will be notified by email or in-app notification in case of substantial changes. Continued use of the Platform after modification constitutes acceptance of the new Terms.</p>
    </LegalPageLayout>
  );
}
